name: Deploy to production

on:
  push:
    branches: ["main"]

env:
  EXPO_DEBUG: "1"

jobs:
  fingerprint:
    name: Fingerprint
    type: fingerprint
    environment: production

  get_ios_build:
    name: Check for existing ios build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: production

  build_ios:
    name: Build iOS
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    type: build
    params:
      platform: ios
      profile: production

  submit_ios_existing_build:
    name: Submit matching iOS build
    needs: [get_ios_build]
    if: ${{ needs.get_ios_build.outputs.build_id }}
    type: submit
    env:
      EXPO_DEBUG: "1"
    params:
      build_id: ${{ needs.get_ios_build.outputs.build_id }}

  submit_ios_new_build:
    name: Submit new iOS build
    needs: [build_ios]
    if: ${{ needs.build_ios.outputs.build_id }}
    type: submit
    env:
      EXPO_DEBUG: "1"
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}

  publish_ios_preview_update:
    name: Publish iOS preview update
    needs: [get_ios_build, build_ios]
    if: ${{ needs.get_ios_build.outputs.build_id || needs.build_ios.outputs.build_id }}
    type: update
    params:
      branch: preview
      platform: ios
